import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { jsPDF } from 'jspdf';

const Section = ({ title, content }) => {
  if (!content) return null;
  return (
    <div className="mb-6">
      <h4 className="text-xs font-semibold uppercase tracking-widest text-primary mb-2">{title}</h4>
      <p className="text-sm text-foreground leading-relaxed whitespace-pre-wrap break-words">{content}</p>
    </div>
  );
};

const exportToPDF = (prd) => {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 50;
  const contentW = pageW - margin * 2;
  let y = margin;

  const addText = (text, fontSize, isBold, color = [30, 30, 30], lineHeightMultiplier = 1.4) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text || '', contentW);
    const lineH = fontSize * lineHeightMultiplier;
    if (y + lines.length * lineH > pageH - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(lines, margin, y);
    y += lines.length * lineH;
  };

  const addSpacer = (h = 12) => { y += h; };
  const addDivider = () => {
    doc.setDrawColor(220, 220, 230);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageW - margin, y);
    y += 16;
  };

  // Title block
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageW, 8, 'F');

  addSpacer(10);
  addText(`${prd.product_name}`, 22, true, [15, 23, 42]);
  addSpacer(4);
  addText('Product Requirements Document', 12, false, [100, 116, 139]);
  addSpacer(8);
  addDivider();

  // Meta row
  if (prd.target_audience) {
    addText('Target Audience', 9, true, [37, 99, 235]);
    addSpacer(2);
    addText(prd.target_audience, 11, false);
    addSpacer(10);
  }

  const sections = [
    { title: 'Executive Summary', content: prd.executive_summary },
    { title: 'Problem Statement', content: prd.problem_statement },
    { title: 'Goal', content: prd.goal },
    { title: 'Proposed Solution', content: prd.proposed_solution },
    { title: 'User Stories', content: prd.user_stories },
    { title: 'Success Metrics (KPIs)', content: prd.success_metrics },
  ];

  sections.forEach(({ title, content }) => {
    if (!content) return;
    addText(title.toUpperCase(), 9, true, [37, 99, 235]);
    addSpacer(4);
    addText(content, 11, false, [30, 30, 50], 1.5);
    addSpacer(16);
  });

  // Footer on every page
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 160);
    doc.text('Generated by InsightSync AI', margin, pageH - 24);
    doc.text(`Page ${i} of ${totalPages}`, pageW - margin, pageH - 24, { align: 'right' });
    doc.setDrawColor(220, 220, 230);
    doc.setLineWidth(0.5);
    doc.line(margin, pageH - 36, pageW - margin, pageH - 36);
  }

  doc.save(`${prd.product_name.replace(/\s+/g, '_')}_PRD.pdf`);
};

export default function PRDViewModal({ prd, open, onClose }) {
  if (!prd) return null;

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-2xl max-h-[85vh] flex flex-col p-0 overflow-hidden">
        {/* Header */}
        <DialogHeader className="px-6 pt-6 pb-4 border-b border-border shrink-0">
          <div className="flex items-start justify-between gap-3">
            <div className="min-w-0 flex-1">
              <DialogTitle className="text-lg break-words">{prd.product_name}</DialogTitle>
              {prd.target_audience && (
                <p className="text-xs text-muted-foreground mt-1">Target: {prd.target_audience}</p>
              )}
            </div>
            <div className="flex items-center gap-2 shrink-0">
              <span className="text-xs px-2 py-0.5 rounded-full border font-medium bg-amber-50 text-amber-700 border-amber-200">
                {prd.status || 'Draft'}
              </span>
              <Button
                size="sm"
                variant="outline"
                onClick={() => exportToPDF(prd)}
                className="gap-1.5 text-xs"
              >
                <Download className="w-3.5 h-3.5" />
                Download PDF
              </Button>
            </div>
          </div>
        </DialogHeader>

        {/* Scrollable content */}
        <div className="flex-1 overflow-y-auto px-6 py-5">
          <Section title="Executive Summary" content={prd.executive_summary} />
          <Section title="Problem Statement" content={prd.problem_statement} />
          <Section title="Goal" content={prd.goal} />
          <Section title="Proposed Solution" content={prd.proposed_solution} />
          <Section title="User Stories" content={prd.user_stories} />
          <Section title="Success Metrics (KPIs)" content={prd.success_metrics} />
        </div>
      </DialogContent>
    </Dialog>
  );
}